name: Clojure CI
on:
  push:
    branches-ignore:
      - master
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@master
        with:
          java-version: 13
      - name: Install JavaScript Dependencies
        run: yarn install
      - name: Install Clojure Dependencies
        run: lein deps
      - name: Run Tests
        run: lein karma
